listening-port=3478
fingerprint
lt-cred-mech

realm=domain

user=stupidboy:hardpassword  

total-quota=100
bps-capacity=0

stale-nonce
no-loopback-peers
no-multicast-peers

min-port=50000
max-port=50100